export const offerConstants = {

    GET_ALL_OFFER_REQUEST : 'GET_ALL_OFFER_REQUEST ',
    GET_ALL_OFFER_SUCCESS: 'GET_ALL_OFFER_SUCCESS ',
    GET_ALL_OFFER_FAILURE : 'GET_ALL_OFFER_FAILURE ',



    ADD_OFFER_REQUEST : 'ADD_OFFER_REQUEST ',
    ADD_OFFER_SUCCESS: 'ADD_OFFER_SUCCESS ',
    ADD_OFFER_FAILURE : 'ADD_OFFER_FAILURE ',


    DELETE_OFFER_REQUEST : 'DELETE_OFFER_REQUEST ',
    DELETE_OFFER_SUCCESS: 'DELETE_OFFER_SUCCESS ',
    DELETE_OFFER_FAILURE : 'DELETE_OFFER_FAILURE ',

    EDIT_OFFER_REQUEST : 'EDIT_OFFER_REQUEST ',
    EDIT_OFFER_SUCCESS: 'EDIT_OFFER_SUCCESS ',
    EDIT_OFFER_FAILURE : 'EDIT_OFFER_FAILURE ',
} 
export const contactConstants = {

    GET_ALL_CONTACT_REQUEST : 'GET_ALL_CONTACT_REQUEST ',
    GET_ALL_CONTACT_SUCCESS: 'GET_ALL_CONTACT_SUCCESS ',
    GET_ALL_CONTACT_FAILURE : 'GET_ALL_CONTACT_FAILURE ',



    ADD_CONTACT_REQUEST : 'ADD_CONTACT_REQUEST ',
    ADD_CONTACT_SUCCESS: 'ADD_CONTACT_SUCCESS ',
    ADD_CONTACT_FAILURE : 'ADD_CONTACT_FAILURE ',


    DELETE_CONTACT_REQUEST : 'DELETE_CONTACT_REQUEST ',
    DELETE_CONTACT_SUCCESS: 'DELETE_CONTACT_SUCCESS ',
    DELETE_CONTACT_FAILURE : 'DELETE_CONTACT_FAILURE ',

    EDIT_CONTACT_REQUEST : 'EDIT_CONTACT_REQUEST ',
    EDIT_CONTACT_SUCCESS: 'EDIT_CONTACT_SUCCESS ',
    EDIT_CONTACT_FAILURE : 'EDIT_CONTACT_FAILURE ',
} 
export const aviseventConstants = {

    GET_ALL_AVISEVENT_REQUEST : 'GET_ALL_AVISEVENT_REQUEST ',
    GET_ALL_AVISEVENT_SUCCESS: 'GET_ALL_AVISEVENT_SUCCESS ',
    GET_ALL_AVISEVENT_FAILURE : 'GET_ALL_AVISEVENT_FAILURE ',



    ADD_AVISEVENT_REQUEST : 'ADD_AVISEVENT_REQUEST ',
    ADD_AVISEVENT_SUCCESS: 'ADD_AVISEVENT_SUCCESS ',
    ADD_AVISEVENT_FAILURE : 'ADD_AVISEVENT_FAILURE ',


    DELETE_AVISEVENT_REQUEST : 'DELETE_AVISEVENT_REQUEST ',
    DELETE_AVISEVENT_SUCCESS: 'DELETE_AVISEVENT_SUCCESS ',
    DELETE_AVISEVENT_FAILURE : 'DELETE_AVISEVENT_FAILURE ',

    EDIT_AVISEVENT_REQUEST : 'EDIT_AVISEVENT_REQUEST ',
    EDIT_AVISEVENT_SUCCESS: 'EDIT_AVISEVENT_SUCCESS ',
    EDIT_AVISEVENT_FAILURE : 'EDIT_AVISEVENT_FAILURE ',
} 
export const formulairedestConstants = {

    GET_ALL_FORMULAIREDEST_REQUEST : 'GET_ALL_FORMULAIREDEST_REQUEST ',
    GET_ALL_FORMULAIREDEST_SUCCESS: 'GET_ALL_FORMULAIREDEST_SUCCESS ',
    GET_ALL_FORMULAIREDEST_FAILURE : 'GET_ALL_FORMULAIREDEST_FAILURE ',



    ADD_FORMULAIREDEST_REQUEST : 'ADD_FORMULAIREDEST_REQUEST ',
    ADD_FORMULAIREDEST_SUCCESS: 'ADD_FORMULAIREDEST_SUCCESS ',
    ADD_FORMULAIREDEST_FAILURE : 'ADD_FORMULAIREDEST_FAILURE ',


    DELETE_FORMULAIREDEST_REQUEST : 'DELETE_FORMULAIREDEST_REQUEST ',
    DELETE_FORMULAIREDEST_SUCCESS: 'DELETE_FORMULAIREDEST_SUCCESS ',
    DELETE_FORMULAIREDEST_FAILURE : 'DELETE_FORMULAIREDEST_FAILURE ',

    EDIT_FORMULAIREDEST_REQUEST : 'EDIT_FORMULAIREDEST_REQUEST ',
    EDIT_FORMULAIREDEST_SUCCESS: 'EDIT_FORMULAIREDEST_SUCCESS ',
    EDIT_FORMULAIREDEST_FAILURE : 'EDIT_FORMULAIREDEST_FAILURE ',
} 

export const formulaireeventConstants = {

    GET_ALL_FORMULAIREEVENT_REQUEST : 'GET_ALL_FORMULAIREEVENT_REQUEST ',
    GET_ALL_FORMULAIREEVENT_SUCCESS: 'GET_ALL_FORMULAIREEVENT_SUCCESS ',
    GET_ALL_FORMULAIREEVENT_FAILURE : 'GET_ALL_FORMULAIREEVENT_FAILURE ',



    ADD_FORMULAIREEVENT_REQUEST : 'ADD_FORMULAIREEVENT_REQUEST ',
    ADD_FORMULAIREEVENT_SUCCESS: 'ADD_FORMULAIREEVENT_SUCCESS ',
    ADD_FORMULAIREEVENT_FAILURE : 'ADD_FORMULAIREEVENT_FAILURE ',


    DELETE_FORMULAIREEVENT_REQUEST : 'DELETE_FORMULAIREEVENT_REQUEST ',
    DELETE_FORMULAIREEVENT_SUCCESS: 'DELETE_FORMULAIREEVENT_SUCCESS ',
    DELETE_FORMULAIREEVENT_FAILURE : 'DELETE_FORMULAIREEVENT_FAILURE ',

    EDIT_FORMULAIREEVENT_REQUEST : 'EDIT_FORMULAIREEVENT_REQUEST ',
    EDIT_FORMULAIREEVENT_SUCCESS: 'EDIT_FORMULAIREEVENT_SUCCESS ',
    EDIT_FORMULAIREEVENT_FAILURE : 'EDIT_FORMULAIREEVENT_FAILURE ',
} 




// export const  CLEAR_ERRORS = 'CLEAR_ERRORS'





/////////new methode
///test

export const ALL_TESTS_REQUEST = 'ALL_TESTS_REQUEST'
export const ALL_TESTS_SUCCESS = 'ALL_TESTS_SUCCESS'
export const ALL_TESTS_FAIL = 'ALL_TESTS_FAIL'

export const NEW_TEST_REQUEST = 'NEW_TEST_REQUEST'
export const NEW_TEST_SUCCESS = 'NEW_TEST_SUCCESS'
export const NEW_TEST_RESET = 'NEW_TEST_RESET'
export const NEW_TEST_FAIL = 'NEW_TEST_FAIL'

export const DELETE_TEST_REQUEST = 'DELETE_TEST_REQUEST'
export const DELETE_TEST_SUCCESS = 'DELETE_TEST_SUCCESS'
export const DELETE_TEST_RESET = 'DELETE_TEST_RESET'
export const DELETE_TEST_FAIL = 'DELETE_TEST_FAIL'

export const UPDATE_TEST_REQUEST = 'UPDATE_TEST_REQUEST'
export const UPDATE_TEST_SUCCESS = 'UPDATE_TEST_SUCCESS'
export const UPDATE_TEST_RESET = 'UPDATE_TEST_RESET'
export const UPDATE_TEST_FAIL = 'UPDATE_TEST_FAIL'

export const TEST_DETAILS_REQUEST = 'TEST_DETAILS_REQUEST'
export const TEST_DETAILS_SUCCESS = 'TEST_DETAILS_SUCCESS'
export const TEST_DETAILS_FAIL = 'TEST_DETAILS_FAIL'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

///destination

export const ALL_DESTINATIONS_REQUEST = 'ALL_DESTINATIONS_REQUEST'
export const ALL_DESTINATIONS_SUCCESS = 'ALL_DESTINATIONS_SUCCESS'
export const ALL_DESTINATIONS_FAIL = 'ALL_DESTINATIONS_FAIL'

export const NEW_DESTINATION_REQUEST = 'NEW_DESTINATION_REQUEST'
export const NEW_DESTINATION_SUCCESS = 'NEW_DESTINATION_SUCCESS'
export const NEW_DESTINATION_RESET = 'NEW_DESTINATION_RESET'
export const NEW_DESTINATION_FAIL = 'NEW_DESTINATION_FAIL'

export const DELETE_DESTINATION_REQUEST = 'DELETE_DESTINATION_REQUEST'
export const DELETE_DESTINATION_SUCCESS = 'DELETE_DESTINATION_SUCCESS'
export const DELETE_DESTINATION_RESET = 'DELETE_DESTINATION_RESET'
export const DELETE_DESTINATION_FAIL = 'DELETE_DESTINATION_FAIL'

export const UPDATE_DESTINATION_REQUEST = 'UPDATE_DESTINATION_REQUEST'
export const UPDATE_DESTINATION_SUCCESS = 'UPDATE_DESTINATION_SUCCESS'
export const UPDATE_DESTINATION_RESET = 'UPDATE_DESTINATION_RESET'
export const UPDATE_DESTINATION_FAIL = 'UPDATE_DESTINATION_FAIL'

export const DESTINATION_DETAILS_REQUEST = 'DESTINATION_DETAILS_REQUEST'
export const DESTINATION_DETAILS_SUCCESS = 'DESTINATION_DETAILS_SUCCESS'
export const DESTINATION_DETAILS_FAIL = 'DESTINATION_DETAILS_FAIL'

////bloghome

export const ALL_BLOGHOMES_REQUEST = 'ALL_BLOGHOMES_REQUEST'
export const ALL_BLOGHOMES_SUCCESS = 'ALL_BLOGHOMES_SUCCESS'
export const ALL_BLOGHOMES_FAIL = 'ALL_BLOGHOMES_FAIL'

export const NEW_BLOGHOME_REQUEST = 'NEW_BLOGHOME_REQUEST'
export const NEW_BLOGHOME_SUCCESS = 'NEW_BLOGHOME_SUCCESS'
export const NEW_BLOGHOME_RESET = 'NEW_BLOGHOME_RESET'
export const NEW_BLOGHOME_FAIL = 'NEW_BLOGHOME_FAIL'

export const DELETE_BLOGHOME_REQUEST = 'DELETE_BLOGHOME_REQUEST'
export const DELETE_BLOGHOME_SUCCESS = 'DELETE_BLOGHOME_SUCCESS'
export const DELETE_BLOGHOME_RESET = 'DELETE_BLOGHOME_RESET'
export const DELETE_BLOGHOME_FAIL = 'DELETE_BLOGHOME_FAIL'

export const UPDATE_BLOGHOME_REQUEST = 'UPDATE_BLOGHOME_REQUEST'
export const UPDATE_BLOGHOME_SUCCESS = 'UPDATE_BLOGHOME_SUCCESS'
export const UPDATE_BLOGHOME_RESET = 'UPDATE_BLOGHOME_RESET'
export const UPDATE_BLOGHOME_FAIL = 'UPDATE_BLOGHOME_FAIL'

export const BLOGHOME_DETAILS_REQUEST = 'BLOGHOME_DETAILS_REQUEST'
export const BLOGHOME_DETAILS_SUCCESS = 'BLOGHOME_DETAILS_SUCCESS'
export const BLOGHOME_DETAILS_FAIL = 'BLOGHOME_DETAILS_FAIL'

///event


export const ALL_EVENTS_REQUEST = 'ALL_EVENTS_REQUEST'
export const ALL_EVENTS_SUCCESS = 'ALL_EVENTS_SUCCESS'
export const ALL_EVENTS_FAIL = 'ALL_EVENTS_FAIL'

export const NEW_EVENT_REQUEST = 'NEW_EVENT_REQUEST'
export const NEW_EVENT_SUCCESS = 'NEW_EVENT_SUCCESS'
export const NEW_EVENT_RESET = 'NEW_EVENT_RESET'
export const NEW_EVENT_FAIL = 'NEW_EVENT_FAIL'

export const DELETE_EVENT_REQUEST = 'DELETE_EVENT_REQUEST'
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS'
export const DELETE_EVENT_RESET = 'DELETE_EVENT_RESET'
export const DELETE_EVENT_FAIL = 'DELETE_EVENT_FAIL'

export const UPDATE_EVENT_REQUEST = 'UPDATE_EVENT_REQUEST'
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS'
export const UPDATE_EVENT_RESET = 'UPDATE_EVENT_RESET'
export const UPDATE_EVENT_FAIL = 'UPDATE_EVENT_FAIL'

export const EVENT_DETAILS_REQUEST = 'EVENT_DETAILS_REQUEST'
export const EVENT_DETAILS_SUCCESS = 'EVENT_DETAILS_SUCCESS'
export const EVENT_DETAILS_FAIL = 'EVENT_DETAILS_FAIL'

//// OFFRE
export const ALL_OFFRES_REQUEST = 'ALL_OFFRES_REQUEST'
export const ALL_OFFRES_SUCCESS = 'ALL_OFFRES_SUCCESS'
export const ALL_OFFRES_FAIL = 'ALL_OFFRES_FAIL'

export const NEW_OFFRE_REQUEST = 'NEW_OFFRE_REQUEST'
export const NEW_OFFRE_SUCCESS = 'NEW_OFFRE_SUCCESS'
export const NEW_OFFRE_RESET = 'NEW_OFFRE_RESET'
export const NEW_OFFRE_FAIL = 'NEW_OFFRE_FAIL'

export const DELETE_OFFRE_REQUEST = 'DELETE_OFFRE_REQUEST'
export const DELETE_OFFRE_SUCCESS = 'DELETE_OFFRE_SUCCESS'
export const DELETE_OFFRE_RESET = 'DELETE_OFFRE_RESET'
export const DELETE_OFFRE_FAIL = 'DELETE_OFFRE_FAIL'

export const UPDATE_OFFRE_REQUEST = 'UPDATE_OFFRE_REQUEST'
export const UPDATE_OFFRE_SUCCESS = 'UPDATE_OFFRE_SUCCESS'
export const UPDATE_OFFRE_RESET = 'UPDATE_OFFRE_RESET'
export const UPDATE_OFFRE_FAIL = 'UPDATE_OFFRE_FAIL'

export const OFFRE_DETAILS_REQUEST = 'OFFRE_DETAILS_REQUEST'
export const OFFRE_DETAILS_SUCCESS = 'OFFRE_DETAILS_SUCCESS'
export const OFFRE_DETAILS_FAIL = 'OFFRE_DETAILS_FAIL'

//////  galleryevent

export const ALL_GALLERYEVENTS_REQUEST = 'ALL_GALLERYEVENTS_REQUEST'
export const ALL_GALLERYEVENTS_SUCCESS = 'ALL_GALLERYEVENTS_SUCCESS'
export const ALL_GALLERYEVENTS_FAIL = 'ALL_GALLERYEVENTS_FAIL'

export const NEW_GALLERYEVENT_REQUEST = 'NEW_GALLERYEVENT_REQUEST'
export const NEW_GALLERYEVENT_SUCCESS = 'NEW_GALLERYEVENT_SUCCESS'
export const NEW_GALLERYEVENT_RESET = 'NEW_GALLERYEVENT_RESET'
export const NEW_GALLERYEVENT_FAIL = 'NEW_GALLERYEVENT_FAIL'

export const DELETE_GALLERYEVENT_REQUEST = 'DELETE_GALLERYEVENT_REQUEST'
export const DELETE_GALLERYEVENT_SUCCESS = 'DELETE_GALLERYEVENT_SUCCESS'
export const DELETE_GALLERYEVENT_RESET = 'DELETE_GALLERYEVENT_RESET'
export const DELETE_GALLERYEVENT_FAIL = 'DELETE_GALLERYEVENT_FAIL'

export const UPDATE_GALLERYEVENT_REQUEST = 'UPDATE_GALLERYEVENT_REQUEST'
export const UPDATE_GALLERYEVENT_SUCCESS = 'UPDATE_GALLERYEVENT_SUCCESS'
export const UPDATE_GALLERYEVENT_RESET = 'UPDATE_GALLERYEVENT_RESET'
export const UPDATE_GALLERYEVENT_FAIL = 'UPDATE_GALLERYEVENT_FAIL'

export const GALLERYEVENT_DETAILS_REQUEST = 'GALLERYEVENT_DETAILS_REQUEST'
export const GALLERYEVENT_DETAILS_SUCCESS = 'GALLERYEVENT_DETAILS_SUCCESS'
export const GALLERYEVENT_DETAILS_FAIL = 'GALLERYEVENT_DETAILS_FAIL'

////hotel

export const ALL_HOTELS_REQUEST = 'ALL_HOTELS_REQUEST'
export const ALL_HOTELS_SUCCESS = 'ALL_HOTELS_SUCCESS'
export const ALL_HOTELS_FAIL = 'ALL_HOTELS_FAIL'

export const NEW_HOTEL_REQUEST = 'NEW_HOTEL_REQUEST'
export const NEW_HOTEL_SUCCESS = 'NEW_HOTEL_SUCCESS'
export const NEW_HOTEL_RESET = 'NEW_HOTEL_RESET'
export const NEW_HOTEL_FAIL = 'NEW_HOTEL_FAIL'

export const DELETE_HOTEL_REQUEST = 'DELETE_HOTEL_REQUEST'
export const DELETE_HOTEL_SUCCESS = 'DELETE_HOTEL_SUCCESS'
export const DELETE_HOTEL_RESET = 'DELETE_HOTEL_RESET'
export const DELETE_HOTEL_FAIL = 'DELETE_HOTEL_FAIL'

export const UPDATE_HOTEL_REQUEST = 'UPDATE_HOTEL_REQUEST'
export const UPDATE_HOTEL_SUCCESS = 'UPDATE_HOTEL_SUCCESS'
export const UPDATE_HOTEL_RESET = 'UPDATE_HOTEL_RESET'
export const UPDATE_HOTEL_FAIL = 'UPDATE_HOTEL_FAIL'

export const HOTEL_DETAILS_REQUEST = 'HOTEL_DETAILS_REQUEST'
export const HOTEL_DETAILS_SUCCESS = 'HOTEL_DETAILS_SUCCESS'
export const HOTEL_DETAILS_FAIL = 'HOTEL_DETAILS_FAIL'

export const SEARCH_HOTELS_START = 'SEARCH_HOTELS_START';
export const SEARCH_HOTELS_SUCCESS = 'SEARCH_HOTELS_SUCCESS';
export const SEARCH_HOTELS_FAILURE = 'SEARCH_HOTELS_FAILURE';



///users


export const ALL_USERS_REQUEST = 'ALL_USERS_REQUEST'
export const ALL_USERS_SUCCESS = 'ALL_USERS_SUCCESS'
export const ALL_USERS_FAIL = 'ALL_USERS_FAIL'

export const NEW_USER_REQUEST = 'NEW_USER_REQUEST'
export const NEW_USER_SUCCESS = 'NEW_USER_SUCCESS'
export const NEW_USER_RESET = 'NEW_USER_RESET'
export const NEW_USER_FAIL = 'NEW_USER_FAIL'

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_RESET = 'DELETE_USER_RESET'
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_RESET = 'UPDATE_USER_RESET'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'


///role

export const ALL_ROLES_REQUEST = 'ALL_ROLES_REQUEST'
export const ALL_ROLES_SUCCESS = 'ALL_ROLES_SUCCESS'
export const ALL_ROLES_FAIL = 'ALL_ROLES_FAIL'

export const NEW_ROLE_REQUEST = 'NEW_ROLE_REQUEST'
export const NEW_ROLE_SUCCESS = 'NEW_ROLE_SUCCESS'
export const NEW_ROLE_RESET = 'NEW_ROLE_RESET'
export const NEW_ROLE_FAIL = 'NEW_ROLE_FAIL'

export const DELETE_ROLE_REQUEST = 'DELETE_ROLE_REQUEST'
export const DELETE_ROLE_SUCCESS = 'DELETE_ROLE_SUCCESS'
export const DELETE_ROLE_RESET = 'DELETE_ROLE_RESET'
export const DELETE_ROLE_FAIL = 'DELETE_ROLE_FAIL'

export const UPDATE_ROLE_REQUEST = 'UPDATE_ROLE_REQUEST'
export const UPDATE_ROLE_SUCCESS = 'UPDATE_ROLE_SUCCESS'
export const UPDATE_ROLE_RESET = 'UPDATE_ROLE_RESET'
export const UPDATE_ROLE_FAIL = 'UPDATE_ROLE_FAIL'

export const ROLE_DETAILS_REQUEST = 'ROLE_DETAILS_REQUEST'
export const ROLE_DETAILS_SUCCESS = 'ROLE_DETAILS_SUCCESS'
export const ROLE_DETAILS_FAIL = 'ROLE_DETAILS_FAIL'


///booking

export const ALL_BOOKINGS_REQUEST = 'ALL_BOOKINGS_REQUEST'
export const ALL_BOOKINGS_SUCCESS = 'ALL_BOOKINGS_SUCCESS'
export const ALL_BOOKINGS_FAIL = 'ALL_BOOKINGS_FAIL'

export const DELETE_BOOKING_REQUEST = 'DELETE_BOOKING_REQUEST'
export const DELETE_BOOKING_SUCCESS = 'DELETE_BOOKING_SUCCESS'
export const DELETE_BOOKING_RESET = 'DELETE_BOOKING_RESET'
export const DELETE_BOOKING_FAIL = 'DELETE_BOOKING_FAIL'

export const UPDATE_BOOKING_REQUEST = 'UPDATE_BOOKING_REQUEST'
export const UPDATE_BOOKING_SUCCESS = 'UPDATE_BOOKING_SUCCESS'
export const UPDATE_BOOKING_RESET = 'UPDATE_BOOKING_RESET'
export const UPDATE_BOOKING_FAIL = 'UPDATE_BOOKING_FAIL'

export const BOOKING_DETAILS_REQUEST = 'BOOKING_DETAILS_REQUEST'
export const BOOKING_DETAILS_SUCCESS = 'BOOKING_DETAILS_SUCCESS'
export const BOOKING_DETAILS_FAIL = 'BOOKING_DETAILS_FAIL'